# Generated by Django 5.1.4 on 2024-12-30 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('fname', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('hode_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Sr_No', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Category_1', models.CharField(max_length=50)),
                ('Item_code', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Item_Category_2', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Dc', models.CharField(max_length=50)),
                ('Supplier', models.CharField(max_length=100)),
                ('ABC_class_Revenue', models.CharField(max_length=50)),
                ('ABC_percentage_Revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('On_hand', models.IntegerField()),
                ('Available_on_hand', models.IntegerField()),
                ('Days_of_supply', models.IntegerField()),
                ('To_ship', models.IntegerField()),
                ('To_receive', models.IntegerField()),
                ('finalized_quantity', models.IntegerField(blank=True, null=True)),
                ('last_submitted_quantity', models.IntegerField(blank=True, null=True, verbose_name='Last submitted quantity')),
            ],
            options={
                'permissions': [('can_upload', 'Can upload file'), ('can_edit', 'Can edit'), ('can_view', 'can view page')],
            },
        ),
        migrations.CreateModel(
            name='ItemAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_finalized_quantity', models.IntegerField(blank=True, null=True)),
                ('new_finalized_quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('update', 'Update'), ('create', 'Create')], max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consensus_planning.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
